### ISSUE TITLE
Lack of examples.

### ISSUE THREAD

**Issue by hetii** [michaelzangl/avr-enc28j60#1]
Hi, could you write some more useful example how to use your lib?

It`s not clear how to initialize it(set ip address etc) and how to test if enc chip is able to communicate (icmp / arping? / example echo server).

Best Regards.

**Comment by michaelzangl** [comment]
Hi. This project is 5 years old. I currently don't have the hardware to test any examples.

To set the IP address, use setMyIp(). This only needs to be done once - it will be stored in EEPROM

You need to set the MAC address in config.h

At the beginning of your program, you should do:
```
initTcpIp();
initEnc();
```

Michael
